### ISSUE TITLE
cross origin issues

### ISSUE THREAD

**Issue by beuted** [r3c/arcadejs#1]
Add a small local server serving files so we don't have to deactivate cross origin on the browser to run the page.

![image](https://user-images.githubusercontent.com/2879233/36749508-45aaa4b0-1bfb-11e8-8548-45fb80b5dc03.png)

**Comment by r3c** [comment]
Mais le mec spoile !

Temporary workaround until this is fixed: `./chrome --allow-file-access-from-files` to disable Chrome specific restriction on file:// protocol (I don't really understand the purpose, seems all other browsers don't require extra permissions).
